# Generated by Django 3.1.3 on 2021-01-20 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CUSTOMER',
            fields=[
                ('customer_Id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('customer_Name', models.CharField(max_length=100)),
                ('phone_No', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('customer_address', models.TextField()),
                ('Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LOCATION',
            fields=[
                ('location_Id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=20)),
                ('pincode', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SALESMAN',
            fields=[
                ('salesman_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('salesman_Name', models.CharField(max_length=100)),
                ('phone_No', models.BigIntegerField()),
                ('email', models.EmailField(max_length=150)),
                ('salesman_Address', models.TextField()),
                ('commission', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='SERVICE',
            fields=[
                ('service_date', models.DateField()),
                ('vehicle_number', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('vehicle_issue', models.CharField(max_length=100)),
                ('delivery_Date', models.DateField(null=True)),
                ('service_cost', models.FloatField(null=True)),
                ('location_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.location')),
                ('service_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ORDER',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_name', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('cost', models.DecimalField(decimal_places=3, max_digits=100000, null=True)),
                ('customer_Id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car.customer')),
                ('location_Id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car.location')),
                ('order_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('salesman_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car.salesman')),
            ],
        ),
    ]
