# Generated by Django 3.1.3 on 2021-01-20 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Username',
        ),
    ]
